# 设置本地依赖路径
export VELOX_TARBALL_DIR="${VELOX_TARBALL_DIR:-/home/tarballs}"
## VELOX SETUP依赖
export VELOX_SETUP_ARROW_URL="file://${VELOX_TARBALL_DIR}/apache-arrow-15.0.0.tar.gz"
export VELOX_SETUP_BOOST_URL="file://${VELOX_TARBALL_DIR}/boost-1.84.0.tar.gz"
export VELOX_SETUP_DUCKDB_URL="file://${VELOX_TARBALL_DIR}/duckdb-v0.8.1.tar.gz"
export VELOX_SETUP_FBTHRIFT_URL="file://${VELOX_TARBALL_DIR}/fbthrift-2024.07.01.00.tar.gz"
export VELOX_SETUP_FIZZ_URL="file://${VELOX_TARBALL_DIR}/fizz-2024.07.01.00.tar.gz"
export VELOX_SETUP_FMT_URL="file://${VELOX_TARBALL_DIR}/fmt-10.1.1.tar.gz"
export VELOX_SETUP_FOLLY_URL="file://${VELOX_TARBALL_DIR}/folly-2024.07.01.00.tar.gz"
export VELOX_SETUP_GFLAGS_URL="file://${VELOX_TARBALL_DIR}/gflags-v2.2.2.tar.gz"
export VELOX_SETUP_GLOG_URL="file://${VELOX_TARBALL_DIR}/glog-v0.6.0.tar.gz"
export VELOX_SETUP_LZO_URL="file://${VELOX_TARBALL_DIR}/lzo-2.10.tar.gz"
export VELOX_SETUP_MVFST_URL="file://${VELOX_TARBALL_DIR}/mvfst-2024.07.01.00.tar.gz"
export VELOX_SETUP_PROTOBUF_URL="file://${VELOX_TARBALL_DIR}/protobuf-all-21.8.tar.gz"
export VELOX_SETUP_SNAPPY_URL="file://${VELOX_TARBALL_DIR}/snappy-1.1.8.tar.gz"
export VELOX_SETUP_STEMMER_URL="file://${VELOX_TARBALL_DIR}/libstemmer_c-2.2.0.tar.gz"
export VELOX_SETUP_WANGLE_URL="file://${VELOX_TARBALL_DIR}/wangle-2024.07.01.00.tar.gz"
## VELOX CMAKE依赖
export VELOX_PROTOBUF_URL="file://${VELOX_TARBALL_DIR}/protobuf-all-21.8.tar.gz"
export VELOX_PROTOBUF_SHA256="$(sha256sum "${VELOX_TARBALL_DIR}/protobuf-all-21.8.tar.gz" | awk '{print $1}')"
export VELOX_SIMDJSON_URL="file://${VELOX_TARBALL_DIR}/simdjson-3.9.3.tar.gz"
export VELOX_SIMDJSON_SHA256="$(sha256sum "${VELOX_TARBALL_DIR}/simdjson-3.9.3.tar.gz" | awk '{print $1}')"
export VELOX_STEMMER_URL="file://${VELOX_TARBALL_DIR}/libstemmer_c-2.2.0.tar.gz"
export VELOX_STEMMER_SHA256="$(sha256sum "${VELOX_TARBALL_DIR}/libstemmer_c-2.2.0.tar.gz" | awk '{print $1}')"
export VELOX_XSIMD_URL="file://${VELOX_TARBALL_DIR}/xsimd-10.0.0.tar.gz"
export VELOX_XSIMD_SHA256="$(sha256sum "${VELOX_TARBALL_DIR}/xsimd-10.0.0.tar.gz" | awk '{print $1}')"
export VELOX_ARROW_URL="file://${VELOX_TARBALL_DIR}/apache-arrow-15.0.0.tar.gz"
export VELOX_ARROW_SHA256="$(sha256sum "${VELOX_TARBALL_DIR}/apache-arrow-15.0.0.tar.gz" | awk '{print $1}')"
export VELOX_GRPC_URL="file://${VELOX_TARBALL_DIR}/grpc-1.48.1.tar.gz"
export VELOX_GRPC_SHA256="$(sha256sum "${VELOX_TARBALL_DIR}/grpc-1.48.1.tar.gz" | awk '{print $1}')"
export VELOX_GTEST_URL="file://${VELOX_TARBALL_DIR}/googletest-1.13.0.tar.gz"
export VELOX_GTEST_SHA256="$(sha256sum "${VELOX_TARBALL_DIR}/googletest-1.13.0.tar.gz" | awk '{print $1}')"
export VELOX_CPR_URL="file://${VELOX_TARBALL_DIR}/cpr-1.10.5.tar.gz"
export VELOX_CPR_SHA256="$(sha256sum "${VELOX_TARBALL_DIR}/cpr-1.10.5.tar.gz" | awk '{print $1}')"
export VELOX_CURL_URL="file://${VELOX_TARBALL_DIR}/curl-8.4.0.tar.xz"
export VELOX_CURL_SHA256="$(sha256sum "${VELOX_TARBALL_DIR}/curl-8.4.0.tar.xz" | awk '{print $1}')"
export VELOX_DUCKDB_URL="file://${VELOX_TARBALL_DIR}/duckdb-0.8.1.tar.gz"
export VELOX_DUCKDB_SHA256="$(sha256sum "${VELOX_TARBALL_DIR}/duckdb-0.8.1.tar.gz" | awk '{print $1}')"
export VELOX_CARES_URL="file://${VELOX_TARBALL_DIR}/c-ares-cares-1_13_0.tar.gz"
export VELOX_CARES_SHA256="$(sha256sum "${VELOX_TARBALL_DIR}/c-ares-cares-1_13_0.tar.gz" | awk '{print $1}')"
export VELOX_SPARK_URL="file://${VELOX_TARBALL_DIR}/spark-3.5.1.tar.gz"
export VELOX_SPARK_SHA256="$(sha256sum "${VELOX_TARBALL_DIR}/spark-3.5.1.tar.gz" | awk '{print $1}')"
## VELOX ARROW依赖
export ARROW_ZSTD_URL="file://${VELOX_TARBALL_DIR}/zstd-1.5.5.tar.gz"
export ARROW_SNAPPY_URL="file://${VELOX_TARBALL_DIR}/snappy-1.1.10.tar.gz"
export ARROW_SUBSTRAIT_URL="file://${VELOX_TARBALL_DIR}/substrait-0.27.0.tar.gz"
export ARROW_THRIFT_URL="file://${VELOX_TARBALL_DIR}/thrift-0.16.0.tar.gz"
export ARROW_ZLIB_URL="file://${VELOX_TARBALL_DIR}/zlib-1.2.13.tar.gz"
export ARROW_RAPIDJSON_URL="file://${VELOX_TARBALL_DIR}/rapidjson-232389d4f1012dddec4ef84861face2d2ba85709.tar.gz"
export ARROW_BOOST_URL="file://${VELOX_TARBALL_DIR}/boost-1.81.0.tar.gz"
export ARROW_GTEST_URL="file://${VELOX_TARBALL_DIR}/googletest-release-1.11.0.tar.gz"
## VELOX GRPC依赖
export VELOX_GRPC_OPENCENSUS_PROTO_MIRROR_URL="file://${VELOX_TARBALL_DIR}/opencensus-proto-0.3.0.tar.gz"
export VELOX_GRPC_OPENCENSUS_PROTO_URL="file://${VELOX_TARBALL_DIR}/opencensus-proto-0.3.0.tar.gz"
export VELOX_GRPC_GOOGLEAPIS_URL="file://${VELOX_TARBALL_DIR}/googleapis-2f9af297c84c55c8b871ba4495e01ade42476c92.tar.gz"
export VELOX_GRPC_XDS_URL="file://${VELOX_TARBALL_DIR}/xds-cb28da3451f158a947dfc45090fe92b07b243bc1.tar.gz"
export VELOX_GRPC_DATA_PLANE_API_URL="file://${VELOX_TARBALL_DIR}/data-plane-api-9c42588c956220b48eb3099d186487c2f04d32ec.tar.gz"